language: go

go:
  - 1.9

addons:
  apt:
    packages:
    - yasm

before_install:
- go get -u github.com/axw/gocov/gocov
- go get -u github.com/alecthomas/gometalinter
- go get -u github.com/mattn/goveralls
- go get -u golang.org/x/tools/cmd/cover
- export PATH=$PATH:$GOPATH/bin
- gometalinter --install --update
- go generate -x ./...

script:
- go test ./... -v -covermode=count -coverprofile=coverage.out

after_success:
- gometalinter -e bindata --deadline=1000s ./...
